export const en = {
  // Onboarding
  onboarding: {
    welcome: 'Welcome to Lumia',
    welcomeSubtitle: 'Your warm, compassionate companion for the IVF journey.',
    letsBegin: "Let's begin",
    language: 'Language',
    whereInJourney: 'Where are you in your journey?',
    whereInJourneySubtitle: "We'll personalize your experience based on where you are.",
    startingFresh: '🌱 Starting Fresh',
    startingFreshDesc: "I haven't started my IVF cycle yet",
    alreadyStarted: '🌿 Already Started',
    alreadyStartedDesc: "I'm in the middle of a cycle",
    cycleHistory: 'Cycle History',
    cycleHistorySubtitle: 'Is this your first IVF cycle?',
    firstCycle: 'Yes, this is my first IVF cycle',
    notFirstCycle: "No, I've been through this before",
    continue: 'Continue',
    clinicAndDoctor: 'Clinic & Doctor',
    clinicHelpText: 'This helps us label your appointments and scan records.',
    clinicName: 'Clinic Name',
    clinicPlaceholder: 'e.g. Klinika Bocian',
    doctorName: "Doctor's Name (Optional)",
    doctorPlaceholder: 'e.g. Dr. Kowalski',
    clinicAddress: 'Clinic Address (Optional)',
    clinicAddressPlaceholder: 'e.g. ul. Inflancka 6, Warsaw',
    clinicPhone: 'Clinic Phone (Optional)',
    clinicPhonePlaceholder: 'e.g. +48 22 123 45 67',
    yourProfile: 'Your Profile',
    yourName: 'Your Name',
    namePlaceholder: 'e.g. Anna',
    trackingMode: 'Tracking Mode',
    solo: 'Solo',
    withPartner: 'With Partner',
    partnerName: "Partner's Name",
    partnerPlaceholder: 'e.g. Marek',
    protocolSetup: 'Protocol Setup',
    selectProtocol: 'Select your protocol type',
    shortProtocol: 'Short Protocol (Antagonist)',
    longProtocol: 'Long Protocol (Agonist)',
    fet: 'FET (Frozen Transfer)',
    startTracking: '🌸 Start Tracking',
    // Cycle tracking step
    yourCycle: 'Your Cycle',
    yourCycleSubtitle: "This helps us predict your next period and send smart reminders.",
    lastPeriodStart: 'When did your last period start?',
    typicalCycleLength: 'Typical cycle length (days)',
    cycleLengthHint: 'Most cycles are 26–32 days. You can always update this later.',
    skipForNow: 'Skip for now',
    continueWithToday: 'Continue with today\'s date',
    alreadyStartedCycleDay: 'Which day of your cycle are you on today?',
    cycleDaySubtitle: 'We\'ll calculate your start date from this.',
  },
  // Dashboard
  dashboard: {
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    partnerSync: 'partner sync',
    nextUp: 'NEXT UP',
    markDone: 'Mark done',
    todaySchedule: "TODAY'S SCHEDULE",
    quickLog: 'QUICK LOG',
    logIt: 'Log it',
    done: 'Done',
    later: 'Later',
    evening: 'Evening',
    dueNow: 'Now · injection due',
    tonight: 'tonight',
    logged: 'logged',
    ofCycle: 'of cycle',
    dose: 'Dose',
    monitoringScan: 'Monitoring scan',
    med: 'Med',
    scan: 'Scan',
    note: 'Note',
    symptom: 'Symp',
    logAnEvent: 'Log an event',
    whatHappenedToday: 'What happened today?',
    recentEvents: 'Recent events',
    noEventsYet: 'No events logged yet. Tap a quick log above to get started!',
    viewAll: 'View all',
    dailyTip: 'Daily Lumia Tip',
    readMore: 'Read more',
    tipText: 'During the stimulation phase, gentle walks can help manage bloating. Keep the movement light to stay comfortable.',
    tomorrow: 'Tomorrow',
    ultrasoundAppointment: 'Ultrasound Appointment',
    // Quick-log category labels
    catMeds: 'Meds &\nInjections',
    catAppointment: 'Appointment',
    catBlood: 'Test / Blood\nWork',
    catScan: 'Scan /\nUltrasound',
    catEmbryo: 'Embryo\nUpdate',
    catMood: 'Mood',
    catPeriod: 'Period',
    // Period log tile (dashboard)
    periodTileTitle: 'My Period',
    periodTileSubtitleNo: 'Tap to log your period start date',
    periodTileSubtitleYes: 'Last period logged',
    periodTileButton: 'Log period',
    periodTileEdit: 'Update',
    periodNextLabel: 'Next expected',
    periodDayLabel: 'Cycle day',
    // Quick-log sheet labels
    logMedication: 'Save Medication',
    saveMedication: 'Save Medication ✓',
    medInjection: 'Injection',
    medOral: 'Oral Medication',
    searchMedicine: 'Search medicine or injection...',
    commonlyUsed: 'Recently Used',
    addCustomMedicine: 'Add custom medicine',
    route: 'Route',
    notes: 'Notes',
    notesPlaceholder: 'e.g. left thigh, no bruising...',
    enterMedName: 'Enter Medicine Name',
    popularMeds: 'Suggested Library',
    recentlyUsedLabel: 'Recently Used',
    firstTimeTitle: 'First Time Adding Meds?',
    firstTimeDesc: 'Type your medicine name above or tap a popular suggestion to start building your library.',
    enterMedNameToSave: 'Enter medicine name to save',
    showMore: '+ {count} more',
    showLess: 'Show less',
    logBloodTest: 'Log Blood Test ✓',
    resultValue: 'Result value (optional)',
    logAppointment: 'Log Appointment ✓',
    appointmentType: 'Appointment type',
    dateTime: 'Date & Time',
    logEmbryo: 'Log Embryo Update ✓',
    updateType: 'Update type',
    // Scan log labels
    saveScanResults: 'Save Scan Results',
    scanType: 'Scan type',
    bloodTestType: 'Test type',
    noScansYet: 'No scans logged yet.',
    follicleMonitoring: 'Follicle monitoring',
    baselineScan: 'Baseline scan',
    liningCheck: 'Lining check',
    triggerResponse: 'Trigger response',
    postRetrieval: 'Post-retrieval',
    other: 'Other',
    rightOvary: 'Right Ovary',
    leftOvary: 'Left Ovary',
    follicles: 'follicles',
    addSize: 'Add size',
    endometrialLining: 'Endometrial lining',
    trilaminarPattern: 'Trilaminar pattern',
    e2Level: 'E2 Level (pmol/L)',
    // Appointment types
    apptMonitoringScan: 'Monitoring Scan',
    apptBloodTest: 'Blood Test',
    apptConsultation: 'Consultation',
    apptEggRetrieval: 'Egg Retrieval',
    apptEmbryoTransfer: 'Embryo Transfer',
    // Mood log
    logMood: 'Log Mood',
    moodSliderLabel: 'How are you feeling today?',
    moodSad: 'Low',
    moodLow: 'Low',
    moodNeutral: 'Okay',
    moodGood: 'Good',
    moodHappy: 'Great',
    moodNotes: 'Notes (optional)',
    moodNotesPlaceholder: 'Anything else on your mind today?',
    // Success state
    loggedSuccessfully: 'Logged successfully!',
    loggedSuccessSubtitle: 'Great job keeping track of your journey.',
    // Schedule collapse
    seeAllItems: 'See all {count} items',
    // Overdue
    overdue: 'Overdue',
    // Period confirmation
    periodConfirmTitle: 'Reset cycle to Day 1?',
    periodConfirmBody: 'Logging a new period will reset your cycle tracking to Day 1.',
    periodConfirmYes: 'Yes, log period',
    periodConfirmNo: 'Cancel',
  },
  // Navigation
  nav: {
    home: 'Home',
    timeline: 'Timeline',
    log: 'Log',
    reports: 'Reports',
    profile: 'Profile',
  },
  // Medication
  medication: {
    title: 'Log',
    actionNeeded: 'ACTION NEEDED',
    upcomingToday: 'UPCOMING TODAY',
    completed: 'COMPLETED',
    dueNow: 'Due now',
    logMedication: 'Log Medication',
    leftSide: 'Left Side',
    rightSide: 'Right Side',
    logIt: 'Log it ✓',
  },
  // Scan
  scan: {
    title: 'Scans',
    leftOvary: 'Left Ovary',
    rightOvary: 'Right Ovary',
    lining: 'Lining',
    e2Level: 'E2 Level',
  },
  // Timeline
  timeline: {
    title: 'Journey',
    today: 'Today',
    cycleDay: 'Cycle Day',
    allEvents: 'All Events',
    injections: 'Injections',
    tests: 'Tests',
    scans: 'Scans',
    filterToday: 'Today',
    filterWeek: 'Week',
    filterCycle: 'Cycle',
    filterAll: 'All',
    logAnEvent: 'Log an Event',
    // Event status badges
    completed: 'Completed',
    pendingResults: 'Pending results',
    historical: 'Historical',
    noEventsTitle: 'No events yet',
    noEventsSubtitle: 'Log your first medication, scan, or mood to see it here.',
    // Scan mini-data labels
    left: 'Left',
    right: 'Right',
    lead: 'Lead',
    phases: {
      Setup: 'Setup',
      Suppression: 'Suppression',
      'Stimulation phase': 'Stimulation',
      Trigger: 'Trigger',
      Retrieval: 'Retrieval',
      Transfer: 'Transfer',
    },
  },
  // Reports
  reports: {
    title: 'Reports',
    cycleSummary: 'Cycle Summary',
    cycleSubtitle: 'IVF/ICSI · Cycle 1 · Day',
    of: 'of',
    // Stat tiles
    injections: 'Injections',
    thisCycle: 'this cycle',
    appointments: 'Appointments',
    attended: 'attended',
    cycleDay: 'Cycle Day',
    ofStimulation: 'of stimulation',
    moodAvg: 'Mood Avg',
    last7days: 'last 7 days',
    moodGood: 'Good',
    // Charts
    e2Levels: 'Estradiol (E2)',
    follicleGrowth: 'Follicle Growth',
    leftLabel: 'Left',
    rightLabel: 'Right',
    // PDF export
    readyForDoctor: 'Ready for your doctor?',
    exportDescription: 'Share a detailed medical breakdown of your cycle, injections, and scan data.',
    includePartnerLogs: "Include partner's logs",
    generatePDF: 'Generate PDF Report',
    generating: 'Generating...',
    reportOpened: 'Report opened!',
    // Legacy keys
    e2Levels_legacy: 'Estradiol (E2) Levels',
    daysTracking: 'Days tracking',
    totalInjections: 'Injections total',
  },
  // Profile
  profile: {
    title: 'Profile',
    withPartner: 'With',
    cycleLabel: 'Cycle',
    language: 'Language',
    languageValue: 'English',
    settings: 'Settings',
    editProfile: 'Edit profile',
    saveChanges: 'Save changes',
    cancelEdit: 'Cancel',
    yourName: 'Your name',
    clinicName: 'Clinic name',
    doctorName: 'Doctor\'s name',
    clinicAddress: 'Clinic address',
    clinicPhone: 'Clinic phone',
    cycleStartDate: 'Cycle start date',
    cycleStartDateHint: 'Changing this will recalculate your current cycle day.',
    devMode: 'Dev Mode (Prototype)',
    simulatePhase: 'Simulate Phase',
    restartOnboarding: 'Restart Onboarding',
    phases: {
      Setup: 'Setup',
      Suppression: 'Suppression (Down-regulation)',
      'Stimulation phase': 'Stimulation (Day 8)',
      Trigger: 'Trigger',
      Retrieval: 'Retrieval',
      Transfer: 'Transfer',
    },
  },
};
