export const pl = {
  // Onboarding
  onboarding: {
    welcome: 'Witaj w Lumia',
    welcomeSubtitle: 'Twój ciepły, empatyczny towarzysz w podróży IVF.',
    letsBegin: 'Zaczynamy',
    language: 'Język',
    whereInJourney: 'Na jakim etapie jesteś?',
    whereInJourneySubtitle: 'Dopasujemy aplikację do Twojej sytuacji.',
    startingFresh: '🌱 Dopiero zaczynam',
    startingFreshDesc: 'Nie zaczęłam jeszcze cyklu IVF',
    alreadyStarted: '🌿 Jestem w trakcie',
    alreadyStartedDesc: 'Jestem w środku cyklu',
    cycleHistory: 'Historia cyklu',
    cycleHistorySubtitle: 'Czy to Twój pierwszy cykl IVF?',
    firstCycle: 'Tak, to mój pierwszy cykl IVF',
    notFirstCycle: 'Nie, mam już za sobą poprzednie cykle',
    continue: 'Dalej',
    clinicAndDoctor: 'Klinika i lekarz',
    clinicHelpText: 'To pomaga nam opisywać Twoje wizyty i badania.',
    clinicName: 'Nazwa kliniki',
    clinicPlaceholder: 'np. Klinika Bocian',
    doctorName: 'Imię i nazwisko lekarza (opcjonalnie)',
    doctorPlaceholder: 'np. Dr Kowalski',
    clinicAddress: 'Adres kliniki (opcjonalnie)',
    clinicAddressPlaceholder: 'np. ul. Inflancka 6, Warszawa',
    clinicPhone: 'Telefon do kliniki (opcjonalnie)',
    clinicPhonePlaceholder: 'np. +48 22 123 45 67',
    yourProfile: 'Twój profil',
    yourName: 'Twoje imię',
    namePlaceholder: 'np. Anna',
    trackingMode: 'Tryb śledzenia',
    solo: 'Sama',
    withPartner: 'Z partnerem',
    partnerName: 'Imię partnera',
    partnerPlaceholder: 'np. Marek',
    protocolSetup: 'Protokół leczenia',
    selectProtocol: 'Wybierz swój protokół',
    shortProtocol: 'Krótki protokół (antagonista)',
    longProtocol: 'Długi protokół (agonista)',
    fet: 'FET (Transfer mrożonych zarodków)',
    startTracking: '🌸 Zacznij śledzenie',
    // Cycle tracking step
    yourCycle: 'Twój cykl',
    yourCycleSubtitle: "To pomoże nam przewidywać następną miesiączkę i wysyłać przypomnienia.",
    lastPeriodStart: 'Kiedy zaczęła się Twoja ostatnia miesiączka?',
    typicalCycleLength: 'Typowa długość cyklu (dni)',
    cycleLengthHint: 'Większość cykli trwa 26–32 dni. Możesz to zmienić później.',
    skipForNow: 'Pomiń na razie',
    continueWithToday: 'Kontynuuj z dzisiejszą datą',
    alreadyStartedCycleDay: 'W którym dniu cyklu jesteś dzisiaj?',
    cycleDaySubtitle: 'Na tej podstawie obliczymy datę rozpoczęcia cyklu.',
  },
  // Dashboard
  dashboard: {
    goodMorning: 'Dzień dobry',
    goodAfternoon: 'Dzień dobry',
    goodEvening: 'Dobry wieczór',
    partnerSync: 'synchronizacja z partnerem',
    nextUp: 'NASTĘPNE',
    markDone: 'Oznacz jako wykonane',
    todaySchedule: 'PLAN NA DZIŚ',
    quickLog: 'SZYBKIE LOGOWANIE',
    logIt: 'Zaloguj',
    done: 'Zrobione',
    later: 'Później',
    evening: 'Wieczór',
    dueNow: 'Teraz · zastrzyk',
    tonight: 'dziś wieczór',
    logged: 'zalogowano',
    ofCycle: 'cyklu',
    dose: 'Dawka',
    monitoringScan: 'USG monitorujące',
    med: 'Lek',
    scan: 'USG',
    note: 'Notatka',
    symptom: 'Objaw',
    logAnEvent: 'Zaloguj zdarzenie',
    whatHappenedToday: 'Co wydarzyło się dzisiaj?',
    recentEvents: 'Ostatnie zdarzenia',
    noEventsYet: 'Brak zdarzeń. Kliknij szybki wpis powyżej, aby rozpocząć!',
    viewAll: 'Zobacz wszystkie',
    dailyTip: 'Porada dnia od Lumia',
    readMore: 'Czytaj więcej',
    tipText: 'W fazie stymulacji lekkie spacery mogą pomóc zmniejszyć uczucie wzdęcia. Zachowaj spokojny ruch, aby być w komforcie.',
    tomorrow: 'Jutro',
    ultrasoundAppointment: 'Wizyta USG',
    // Quick-log category labels (used in the 2×3 grid)
    catMeds: 'Leki i\nzastrzyki',
    catAppointment: 'Wizyta',
    catBlood: 'Test / Badanie\nkrwi',
    catScan: 'USG /\nScan',
    catEmbryo: 'Aktualizacja\nzarodka',
    catMood: 'Nastrój',
    catPeriod: 'Miesiączka',
    // Period log tile
    periodTileTitle: 'Moja miesiączka',
    periodTileSubtitleNo: 'Dotknij, aby zalogować datę początku',
    periodTileSubtitleYes: 'Ostatnia miesiączka zalogowana',
    periodTileButton: 'Zaloguj',
    periodTileEdit: 'Aktualizuj',
    periodNextLabel: 'Następna prognozowana',
    periodDayLabel: 'Dzień cyklu',
    // Quick-log sheet labels
    logMedication: 'Zapisz lek',
    saveMedication: 'Zapisz lek ✓',
    medInjection: 'Zastrzyk',
    medOral: 'Lek doustny',
    searchMedicine: 'Szukaj leku lub zastrzyku...',
    commonlyUsed: 'Ostatnio używane',
    addCustomMedicine: 'Dodaj własny lek',
    route: 'Droga podania',
    notes: 'Notatki',
    notesPlaceholder: 'np. lewa uda, bez siniaków...',
    enterMedName: 'Wpisz nazwę leku',
    popularMeds: 'Sugerowana biblioteka',
    recentlyUsedLabel: 'Ostatnio używane',
    firstTimeTitle: 'Dodajesz leki po raz pierwszy?',
    firstTimeDesc: 'Wpisz nazwę leku powyżej lub wybierz z sugerowanej biblioteki, aby zacząć.',
    enterMedNameToSave: 'Wpisz nazwę leku, aby zapisać',
    showMore: '+ {count} więcej',
    showLess: 'Pokaż mniej',
    logBloodTest: 'Zapisz badanie ✓',
    resultValue: 'Wartość wyniku (opcjonalnie)',
    logAppointment: 'Zapisz wizytę ✓',
    appointmentType: 'Rodzaj wizyty',
    dateTime: 'Data i godzina',
    logEmbryo: 'Zapisz aktualizację ✓',
    updateType: 'Rodzaj aktualizacji',
    // Scan log labels
    saveScanResults: 'Zapisz wyniki skanu',
    scanType: 'Rodzaj skanu',
    bloodTestType: 'Rodzaj badania',
    noScansYet: 'Brak zapisanych badań.',
    follicleMonitoring: 'Monitorowanie pęcherzyków',
    baselineScan: 'Skan bazowy',
    liningCheck: 'Ocena endometrium',
    triggerResponse: 'Odpowiedź na trigger',
    postRetrieval: 'Po pobraniu',
    other: 'Inne',
    rightOvary: 'Prawy jajnik',
    leftOvary: 'Lewy jajnik',
    follicles: 'pęcherzyki',
    addSize: 'Dodaj rozmiar',
    endometrialLining: 'Endometrium',
    trilaminarPattern: 'Wzorzec trójwarstwowy',
    e2Level: 'Poziom E2 (pmol/L)',
    // Appointment types
    apptMonitoringScan: 'USG monitorujące',
    apptBloodTest: 'Badanie krwi',
    apptConsultation: 'Konsultacja',
    apptEggRetrieval: 'Pobieranie komórek jajowych',
    apptEmbryoTransfer: 'Transfer zarodka',
    // Mood log
    logMood: 'Zapisz nastrój',
    moodSliderLabel: 'Jak się czujesz dzisiaj?',
    moodSad: 'Źle',
    moodLow: 'Słabo',
    moodNeutral: 'Tak sobie',
    moodGood: 'Dobrze',
    moodHappy: 'Świetnie',
    moodNotes: 'Notatki (opcjonalnie)',
    moodNotesPlaceholder: 'Coś jeszcze na myśli?',
    // Success state
    loggedSuccessfully: 'Zalogowano pomyślnie!',
    loggedSuccessSubtitle: 'Świetna robota — śledzisz swoją podróż.',
    // Schedule collapse
    seeAllItems: 'Zobacz wszystkie ({count})',
    // Overdue
    overdue: 'Zaległe',
    // Period confirmation
    periodConfirmTitle: 'Zresetować cykl do Dnia 1?',
    periodConfirmBody: 'Zapisanie nowej miesiączki zresetuje Twoje śledzenie cyklu do Dnia 1.',
    periodConfirmYes: 'Tak, zapisz miesiączkę',
    periodConfirmNo: 'Anuluj',
  },
  // Navigation
  nav: {
    home: 'Pulpit',
    timeline: 'Oś czasu',
    log: 'Logowanie',
    reports: 'Raporty',
    profile: 'Profil',
  },
  // Medication
  medication: {
    title: 'Logowanie leków',
    actionNeeded: 'WYMAGA UWAGI',
    upcomingToday: 'ZAPLANOWANE NA DZIŚ',
    completed: 'WYKONANE',
    dueNow: 'Teraz',
    logMedication: 'Zaloguj lek',
    leftSide: 'Lewa strona',
    rightSide: 'Prawa strona',
    logIt: 'Zaloguj ✓',
  },
  // Scan
  scan: {
    title: 'USG i badania',
    leftOvary: 'Lewy jajnik',
    rightOvary: 'Prawy jajnik',
    lining: 'Endometrium',
    e2Level: 'Poziom E2',
  },
  // Timeline
  timeline: {
    title: 'Oś czasu',
    today: 'Dziś',
    cycleDay: 'Dzień cyklu',
    allEvents: 'Wszystkie',
    injections: 'Zastrzyki',
    tests: 'Badania',
    scans: 'Skany',
    filterToday: 'Dziś',
    filterWeek: 'Tydzień',
    filterCycle: 'Cykl',
    filterAll: 'Wszystko',
    logAnEvent: 'Zaloguj zdarzenie',
    // Event status badges
    completed: 'Wykonano',
    pendingResults: 'Oczekiwanie na wyniki',
    historical: 'Historyczne',
    noEventsTitle: 'Brak zdarzeń',
    noEventsSubtitle: 'Zaloguj pierwszy lek, badanie lub nastrój, aby zobaczyć go tutaj.',
    // Scan mini-data labels
    left: 'Lewy',
    right: 'Prawy',
    lead: 'Wiodący',
    phases: {
      Setup: 'Konfiguracja',
      Suppression: 'Supresja',
      'Stimulation phase': 'Stymulacja',
      Trigger: 'Trigger',
      Retrieval: 'Pobranie',
      Transfer: 'Transfer',
    },
  },
  // Reports
  reports: {
    title: 'Raporty',
    cycleSummary: 'Podsumowanie cyklu',
    cycleSubtitle: 'IVF/ICSI · Cykl 1 · Dzień',
    of: 'z',
    // Stat tiles
    injections: 'Zastrzyki',
    thisCycle: 'w tym cyklu',
    appointments: 'Wizyty',
    attended: 'odbyte',
    cycleDay: 'Dzień cyklu',
    ofStimulation: 'stymulacji',
    moodAvg: 'Nastrój (śr.)',
    last7days: 'ostatnie 7 dni',
    moodGood: 'Dobrze',
    // Charts
    e2Levels: 'Estradiol (E2)',
    follicleGrowth: 'Wzrost pęcherzyków',
    leftLabel: 'Lewy',
    rightLabel: 'Prawy',
    // PDF export
    readyForDoctor: 'Gotowe dla lekarza?',
    exportDescription: 'Udostępnij szczegółowe zestawienie medyczne Twojego cyklu, zastrzyków i wyników badań.',
    includePartnerLogs: 'Dołącz notatki partnera',
    generatePDF: 'Generuj raport PDF',
    generating: 'Generowanie...',
    reportOpened: 'Raport otwarty!',
    // Legacy keys kept for backward compat
    e2Levels_legacy: 'Poziom estradiolu (E2)',
    daysTracking: 'Dni śledzenia',
    totalInjections: 'Łącznie zastrzyków',
  },
  // Profile
  profile: {
    title: 'Profil',
    withPartner: 'Z partnerem',
    cycleLabel: 'Cykl',
    language: 'Język',
    languageValue: 'Polski',
    settings: 'Ustawienia',
    editProfile: 'Edytuj profil',
    saveChanges: 'Zapisz zmiany',
    cancelEdit: 'Anuluj',
    yourName: 'Twoje imię',
    clinicName: 'Nazwa kliniki',
    doctorName: 'Lekarz',
    clinicAddress: 'Adres kliniki',
    clinicPhone: 'Telefon kliniki',
    cycleStartDate: 'Data rozpoczęcia cyklu',
    cycleStartDateHint: 'Zmiana tej daty przeliczy Twój aktualny dzień cyklu.',
    devMode: 'Tryb deweloperski (Prototyp)',
    simulatePhase: 'Symuluj fazę',
    restartOnboarding: 'Uruchom onboarding ponownie',
    phases: {
      Setup: 'Konfiguracja',
      Suppression: 'Supresja (Down-regulation)',
      'Stimulation phase': 'Stymulacja (Dzień 8)',
      Trigger: 'Trigger',
      Retrieval: 'Pobranie',
      Transfer: 'Transfer',
    },
  },
};
